//
//  ImageDetailsInteractor.swift
//  Nasa Gallary App
//
//  Created by ADMIN on 01/09/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ImageDetailsBusinessLogic
{
 
}

protocol ImageDetailsDataStore
{
    var selectedImageModelIndex: Int? { get set }
    var imageDataArray:  [NasaImageList.ImageViewModel]? { get set }
}

class ImageDetailsInteractor: ImageDetailsBusinessLogic, ImageDetailsDataStore
{
    var selectedImageModelIndex: Int?
    var imageDataArray: [NasaImageList.ImageViewModel]?

    
  var presenter: ImageDetailsPresentationLogic?
  var worker: ImageDetailsWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: ImageDetails.Something.Request)
  {
   
  }
}
