# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'Nasa Gallary App' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

pod 'Kingfisher'

  # Pods for Nasa Gallary App

  target 'Nasa Gallary AppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Nasa Gallary AppUITests' do
    # Pods for testing
  end

end
