//
//  NasaImageListWorker.swift
//  Nasa Gallary App
//
//  Created by SHAILESH on 01/09/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class NasaImageListWorker
{
    func getImageDataFromJson(completionHandler:@escaping ([NasaImageList.ImageViewModel]?, _ message: String?,_ statusCode : Int?) -> Void) {
        
          if let path = Bundle.main.path(forResource: "data", ofType: "json") {
                  do {
                        let data = try Data(contentsOf: URL(fileURLWithPath: path), options: .mappedIfSafe)

                      do {
                          let decoder = JSONDecoder()
                          //                            decoder.dateDecodingStrategy = .formatted(DateFormatter.customFormat)
                          let decodedValue = try decoder.decode(Array<NasaImageList.ImageViewModel>.self, from: data)
                          completionHandler(decodedValue    ,"List feteched successfully",1)

                      } catch (let error) {
                          completionHandler(nil,"\(error.localizedDescription)",0)
                      }

                  }catch(let error) {
                      completionHandler(nil,"\(error.localizedDescription)",0)
                  }

              }
    }
}
