//
//  NasaImageListModels.swift
//  Nasa Gallary App
//
//  Created by SHAILESH on 01/09/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum NasaImageList
{
    class ImageViewModel:Decodable {
        
        init() {
            
        }
        //variable for image url
        var hdurl: String?
       //key to replace
        enum CodingKeys: String, CodingKey {
            
            case hdurl

        }
        required init(from decoder: Decoder) throws {
            
            let values = try decoder.container(keyedBy: CodingKeys.self)
            hdurl = try values.decodeIfPresent(String.self, forKey: .hdurl)
        }
    }
}
