//
//  NasaImageListInteractor.swift
//  Nasa Gallary App
//
//  Created by SHAILESH on 01/09/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol NasaImageListBusinessLogic
{
  func fetchImageData()
}

protocol NasaImageListDataStore
{
  var selectedImageModel: NasaImageList.ImageViewModel? { get set }
}

class NasaImageListInteractor: NasaImageListBusinessLogic, NasaImageListDataStore
{
  var selectedImageModel: NasaImageList.ImageViewModel?
    
  var presenter: NasaImageListPresentationLogic?
  var worker: NasaImageListWorker?
  //var name: String = ""
  
  // MARK: Do something
  
    func fetchImageData()
  {
    worker = NasaImageListWorker()
      worker?.getImageDataFromJson(completionHandler: {response,message,statusCode in
          
          self.presenter?.presentFetchedImageData(response: response, message: message ?? "", statusCode: statusCode ?? 0)
          
      })
  }
}
