//
//  ImageDetailsRouter.swift
//  Nasa Gallary App
//
//  Created by ADMIN on 01/09/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol ImageDetailsRoutingLogic
{
  
}

protocol ImageDetailsDataPassing
{
  var dataStore: ImageDetailsDataStore? { get }
}

class ImageDetailsRouter: NSObject, ImageDetailsRoutingLogic, ImageDetailsDataPassing
{
  weak var viewController: ImageDetailsViewController?
  var dataStore: ImageDetailsDataStore?
  
 
}
