//
//  NasaImageListPresenter.swift
//  Nasa Gallary App
//
//  Created by ADMIN on 01/09/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol NasaImageListPresentationLogic
{
    func presentFetchedImageData(response: [NasaImageList.ImageViewModel]?,message:String,statusCode:Int)
}

class NasaImageListPresenter: NasaImageListPresentationLogic
{
  weak var viewController: NasaImageListDisplayLogic?
  
  // MARK: Do something
  
    func presentFetchedImageData(response: [NasaImageList.ImageViewModel]?,message:String,statusCode:Int)
  {
      
      viewController?.didReceiveFetchedImageData(response: response, message: message, statusCode: statusCode)
  }
}
