//
//  NasaImageListModels.swift
//  Nasa Gallary App
//
//  Created by ADMIN on 01/09/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum NasaImageList
{
    class ImageViewModel:Decodable {
        
        init() {
            
        }
      
        var hdurl: String?
        var copyright: String?
        var explanation: String?
        var title: String?
        var url: String?
        var captured_date:String?
        
       //key to replace
        enum CodingKeys: String, CodingKey {
            
            case hdurl
            case copyright
            case explanation
            case title
            case date
            case url

        }
        required init(from decoder: Decoder) throws {
            
            let values = try decoder.container(keyedBy: CodingKeys.self)
            hdurl = try values.decodeIfPresent(String.self, forKey: .hdurl)
            copyright = try values.decodeIfPresent(String.self, forKey: .copyright)
            explanation = try values.decodeIfPresent(String.self, forKey: .explanation)
            title = try values.decodeIfPresent(String.self, forKey: .title)
            
            url = try values.decodeIfPresent(String.self, forKey: .url)
            
            captured_date = try values.decodeIfPresent(String.self, forKey: .date)
        }
    }
}
