//
//  NasaImageListRouter.swift
//  Nasa Gallary App
//
//  Created by ADMIN on 01/09/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol NasaImageListRoutingLogic
{
  func routeToshowDetailsSegue(segue: UIStoryboardSegue?)
}

protocol NasaImageListDataPassing
{
  var dataStore: NasaImageListDataStore? { get }
}

class NasaImageListRouter: NSObject, NasaImageListRoutingLogic, NasaImageListDataPassing
{
  weak var viewController: NasaImageListViewController?
  var dataStore: NasaImageListDataStore?
  
  // MARK: Routing
  
  func routeToshowDetailsSegue(segue: UIStoryboardSegue?)
  {
    if let segue = segue {
      let destinationVC = segue.destination as! ImageDetailsViewController
      var destinationDS = destinationVC.router!.dataStore!
      passDataToSomewhere(source: dataStore!, destination: &destinationDS)
    } else {
      let storyboard = UIStoryboard(name: "Main", bundle: nil)
      let destinationVC = storyboard.instantiateViewController(withIdentifier: "ImageDetailsViewController") as! ImageDetailsViewController
      var destinationDS = destinationVC.router!.dataStore!
      passDataToSomewhere(source: dataStore!, destination: &destinationDS)
      navigateToSomewhere(source: viewController!, destination: destinationVC)
    }
  }

  // MARK: Navigation
  
  func navigateToSomewhere(source: NasaImageListViewController, destination: ImageDetailsViewController)
  {
    source.show(destination, sender: nil)
  }
  
  // MARK: Passing data
  
  func passDataToSomewhere(source: NasaImageListDataStore, destination: inout ImageDetailsDataStore)
  {
      destination.selectedImageModelIndex = self.viewController?.collectionView?.indexPathsForSelectedItems?.first?.row ?? 0
      destination.imageDataArray = self.viewController?.imageArray
  }
}
